Tehnoforest/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Tehnoforest.Services.Data;
using Tehnoforest.Services.Data.Interfaces;
using ShoppingCartViewModel = Tehnoforest.Services.Data.ShoppingCartViewModel;

namespace Tehnoforest.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IProductService productService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService ordersService;

        public OrdersController(IProductService productService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            this.productService = productService;
            this._shoppingCart = shoppingCart;
            this.ordersService = ordersService;
        }
        public async Task<IActionResult> All()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartViewModel()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await productService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await productService.GetProductByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }
    }
}

Tehnoforest/Controllers/UserController.cs
namespace Tehnoforest.Controllers
{
    using Microsoft.AspNetCore.Authentication;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
	
	using Tehnoforest.Data.Models;
    using Tehnoforest.Web.ViewModels.User;

    using static Tehnoforest.Common.NotificationMessagesConstants;

    public class UserController : Controller
	{
		private readonly SignInManager<ApplicationUser> signInManager;
		private readonly UserManager<ApplicationUser> userManager;

        public UserController(SignInManager<ApplicationUser> signInManager,
                             UserManager<ApplicationUser> userManager)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
        }

        [HttpGet]
		public IActionResult Register()
		{
			return View();
		}

        [HttpPost]
        //[ValidateRecaptcha(Action = nameof(Register),
          //  ValidationFailedAction = ValidationFailedAction.ContinueRequest)]
        public async Task<IActionResult> Register(RegisterFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            ApplicationUser user = new ApplicationUser()
            {
                FirstName = model.FirstName,
                LastName = model.LastName
            };

            await userManager.SetEmailAsync(user, model.Email);
            await userManager.SetUserNameAsync(user, model.Email);

            IdentityResult result =
                await userManager.CreateAsync(user, model.Password);

            if (!result.Succeeded)
            {
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

                return View(model);
            }

            await signInManager.SignInAsync(user, false);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Login(string? returnUrl = null)
        {
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            LoginFormModel model = new LoginFormModel()
            {
                ReturnUrl = returnUrl
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var result =
                await signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);

            if (!result.Succeeded)
            {
                TempData[ErrorMessage] =
                    "Нещо се обърка! Моля опитайте по-късно или се свържете с администраторите!";

                return View(model);
            }

            return Redirect(model.ReturnUrl ?? "/Home/Index");
        }
    }
}

Tehnoforest/Views/Shared/_AutomowerFormPartial.cshtml
@model AutomowerFormModel
<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Model"></label>
                <input asp-for="Model" class="form-control" placeholder="Модел">
                <span asp-validation-for="Model" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WorkingAreaCapacity"></label>
                <input asp-for="WorkingAreaCapacity" class="form-control"
                       placeholder="Работна площ">
                <span asp-validation-for="WorkingAreaCapacity" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SlopePerformance"></label>
                <input asp-for="SlopePerformance" class="form-control"
                       placeholder="Максимален наклон на работа">
                <span asp-validation-for="SlopePerformance" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BoundaryType"></label>
                <input asp-for="BoundaryType" class="form-control"
                       placeholder="Вид на ограничението">
                <span asp-validation-for="BoundaryType" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
<textarea asp-for="Description" rows="4" class="form-control"
          placeholder="Описание"></textarea>
                <span asp-validation-for="Description" class="small text-
danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Линк на изображение">
                <span asp-validation-for="ImageUrl" class="small text-
danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" placeholder="Цена">
                <span asp-validation-for="Price" class="small text-
danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Availability"></label>
                <input asp-for="Availability" class="form-control" placeholder="Наличност">
                <span asp-validation-for="Availability" class="small text-
danger"></span>
            </div>
            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Запази" />
            </div>
        </form>
    </div>
</div>

Tehnoforest/Views/Shared/_AutomowerPartial.cshtml
<head>
    <link rel="stylesheet" href="~/css/allProducts.css" asp-append-version="true" />
</head>
@model AutomowerAllViewModel
<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="@Model.ImageUrl" alt="Chainsaw Image">
        <div class="card-body text-left">
            <h6>Косачки-роботи</h6>
            <h4>AUTOMOWER® @Model.Model</h4>
            <h6>Максимална работна площ: <b>@Model.WorkingAreaCapacity m²</b></h6>
            <h6>Максимален наклон на работа: <b>@Model.MaximumSlopePerformance %</b> </h6>                                                                                                                                                                                                                      
            <h6>
                Цена:
                <b>@String.Format("{0:f2}", Model.Price) BGN</b>
            </h6>
            <br />
            <a asp-controller="Automower" asp-action="Details" asp-route-id="@Model.Id"
               class="btn btn-success">Детайли</a>
            <a class="btn btn-success text-white"
               asp-controller="Orders"
               asp-action="AddItemToShoppingCart"
               asp-route-id="@Model.Id">
                <i class="bi bi-cart-plus"></i> Добави в количката)
            </a>
        </div>
    </div>
</div>

Tehnoforest/Views/Shared/_ChainsawFormPartial.cshtml
@model ChainsawFormModel
<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Model"></label>
                <input asp-for="Model" class="form-control" placeholder="Модел">
                <span asp-validation-for="Model" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Power"></label>
                <input asp-for="Power" class="form-control"
                       placeholder="Мощност">
                <span asp-validation-for="Power" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CylinderDisplacement"></label>
                <input asp-for="CylinderDisplacement" class="form-control"
                       placeholder="Обем на цилиндър">
                <span asp-validation-for="CylinderDisplacement" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BarLength"></label>
                <input asp-for="BarLength" class="form-control"
                       placeholder="Дължина на шина">
                <span asp-validation-for="BarLength" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
<textarea asp-for="Description" rows="4" class="form-control"
          placeholder="Описание"></textarea>
                <span asp-validation-for="Description" class="small text-
danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Линк на изображение">
                <span asp-validation-for="ImageUrl" class="small text-
danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" placeholder="Цена">
                <span asp-validation-for="Price" class="small text-
danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Availability"></label>
                <input asp-for="Availability" class="form-control" placeholder="Наличност">
                <span asp-validation-for="Availability" class="small text-
danger"></span>
            </div>
            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Запази" />
            </div>
        </form>
    </div>
</div>

Tehnoforest/Views/Shared/_ChainsawPartial.cshtml
<head>
    <link rel="stylesheet" href="~/css/allProducts.css" asp-append-version="true" />
</head>
@model ChainsawAllViewModel
<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="@Model.ImageUrl" alt="Chainsaw Image">
        <div class="card-body text-left">
            <h6>Верижни триони</h6>
            <h4>@Model.Model</h4>
            <h6>Мощност: <b>@Model.Power kW</b></h6>
            <h6>Обем на цилиндъра: <b>@Model.CylinderDisplacement cm³</b> </h6>
            <h6>
                Цена:
                <b>@String.Format("{0:f2}", Model.Price) BGN</b>
            </h6>
            <br />
            <a asp-controller="Chainsaw" asp-action="Details" asp-route-id="@Model.Id"
               class="btn btn-success">Детайли</a>
            <a class="btn btn-success text-white"
               asp-controller="Orders"
               asp-action="AddItemToShoppingCart"
               asp-route-id="@Model.Id">
                <i class="bi bi-cart-plus"></i> Добави в количката)
            </a>
        </div>
    </div>
</div>

Tehnoforest/Views/Shared/_GardenTractorFormPartial.cshtml
@model GardenTractorFormModel
<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Model"></label>
                <input asp-for="Model" class="form-control" placeholder="Модел">
                <span asp-validation-for="Model" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CylinderDisplacement"></label>
                <input asp-for="CylinderDisplacement" class="form-control"
                       placeholder="Обем на цилиндъра">
                <span asp-validation-for="CylinderDisplacement" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NetPower"></label>
                <input asp-for="NetPower" class="form-control"
                       placeholder="Ефективна мощност при зададени обороти Енергия">
                <span asp-validation-for="NetPower" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CuttingWidth"></label>
                <input asp-for="CuttingWidth" class="form-control"
                       placeholder="Ширина на косене">
                <span asp-validation-for="CuttingWidth" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CuttingHeightMax"></label>
                <input asp-for="CuttingHeightMax" class="form-control"
                       placeholder="Максимална височина на косене">
                <span asp-validation-for="CuttingHeightMax" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CuttingHeightMin"></label>
                <input asp-for="CuttingHeightMin" class="form-control"
                       placeholder="Минимална височина на косене">
                <span asp-validation-for="CuttingHeightMin" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
<textarea asp-for="Description" rows="4" class="form-control"
          placeholder="Описание"></textarea>
                <span asp-validation-for="Description" class="small text-
danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Линк на изображение">
                <span asp-validation-for="ImageUrl" class="small text-
danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" placeholder="Цена">
                <span asp-validation-for="Price" class="small text-
danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Availability"></label>
                <input asp-for="Availability" class="form-control" placeholder="Наличност">
                <span asp-validation-for="Availability" class="small text-
danger"></span>
            </div>
            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Запази" />
            </div>
        </form>
    </div>
</div>

Tehnoforest/Views/Shared/_GardenTractorPartial.cshtml
<head>
    <link rel="stylesheet" href="~/css/allProducts.css" asp-append-version="true" />
</head>
@model GardenTractorAllViewModel
<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="@Model.ImageUrl" alt="Chainsaw Image">
        <div class="card-body text-left">
            <h6>Градински трактори</h6>
            <h4>@Model.Model</h4>
            <h6>Мощност: <b>@Model.NetPower kW</b></h6>
            <h6>Обем на цилиндъра: <b>@Model.CylinderDisplacement cm³</b> </h6>
            <h6>
                Цена:
                <b>@String.Format("{0:f2}", Model.Price) BGN</b>
            </h6>
            <br />
            <a asp-controller="GardenTractor" asp-action="Details" asp-route-id="@Model.Id"
               class="btn btn-success">Детайли</a>
            <a class="btn btn-success text-white"
               asp-controller="Orders"
               asp-action="AddItemToShoppingCart"
               asp-route-id="@Model.Id">
                <i class="bi bi-cart-plus"></i> Добави в количката)
            </a>
        </div>
    </div>
</div>

Tehnoforest/Views/Shared/_GrassTrimmerPartial.cshtml
<head>
    <link rel="stylesheet" href="~/css/allProducts.css" asp-append-version="true" />
</head>
@model GrassTrimmerAllViewModel
<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="@Model.ImageUrl" alt="Grass Trimmer Image">
        <div class="card-body text-left">
            <h6>Моторни коси</h6>
            <h4>@Model.Model</h4>
            <h6>Ширина на косене: <b>@Model.CuttingWidth cm</b></h6>
            <h6>Мощност: <b>@Model.Power kW</b> </h6>
            <h6>
                Цена:
                <b>@String.Format("{0:f2}", Model.Price) BGN</b>
            </h6>
            <br />
            <a asp-controller="GrassTrimmer" asp-action="Details" asp-route-id="@Model.Id"
               class="btn btn-success">Детайли</a>
            <a class="btn btn-success text-white"
               asp-controller="Orders"
               asp-action="AddItemToShoppingCart"
               asp-route-id="@Model.Id">
                <i class="bi bi-cart-plus"></i> Добави в количката)
            </a>
        </div>
    </div>
</div>

Tehnoforest/Views/Shared/_LawnMowerPartial.cshtml
<head>
    <link rel="stylesheet" href="~/css/allProducts.css" asp-append-version="true" />
</head>
@model LawnMowerAllViewModel
<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="@Model.ImageUrl" alt="Chainsaw Image">
        <div class="card-body text-left">
            <h6>Косачки</h6>
            <h4>@Model.Model</h4>
            <h6>Максимална работна площ: <b>@Model.WorkingAreaCapacity m²</b></h6>
            <h6>Задвижваща система: <b>@Model.DriveSystem %</b> </h6>
            <h6>
                Цена:
                <b>@String.Format("{0:f2}", Model.Price) BGN</b>
            </h6>
            <br />
            <a asp-controller="LawnMower" asp-action="Details" asp-route-id="@Model.Id"
               class="btn btn-success">Детайли</a>
            <a class="btn btn-success text-white"
               asp-controller="Orders"
               asp-action="AddItemToShoppingCart"
               asp-route-id="@Model.Id">
                <i class="bi bi-cart-plus"></i> Добави в количката)
            </a>
        </div>
    </div>
</div>

Tehnoforest/Views/Shared/_Layout.cshtml
@using static Tehnoforest.Common.GeneralApplicationConstants;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tehnoforest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Tehnoforest.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <partial name="_NotificationsPartial" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" style="width:70px; height:70px"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chainsaw" asp-action="All">Верижни триони</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LawnMower" asp-action="All">Косачки</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Automower" asp-action="All">Косачки-роботи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GrassTrimmer" asp-action="All">Моторни коси</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GardenTractor" asp-action="All">Градински трактори</a>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="dropbtn">Сервиз</button>
                                <div class="dropdown-content">
                                    <a class="nav-link text-dark" asp-controller="RepairServiceProduct" asp-action="Info">Сервизи</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="RepairServiceProduct" asp-action="All">История на ремонтите</a>
                                    @if (this.User.IsInRole("Administrator"))
                                    {
                                        <a class="nav-link text-dark" asp-controller="RepairServiceProduct" asp-action="Add">Добави машина за ремонт</a>
                                    }

                                </div>
                            </div>
                        </li>
                        @if (this.User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <div class="dropdown">
                                    <button class="dropbtn">Добави продукт</button>
                                    <div class="dropdown-content">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Chainsaw" asp-action="Add">Добави моторен трион</a>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Automower" asp-action="Add">Добави автоматична косачка</a>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="GardenTractor" asp-action="Add">Добави градински трактор</a>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="GrassTrimmer" asp-action="Add">Добави моторна коса</a>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="LawnMower" asp-action="Add">Добави косачка</a>
                                    </div>
                                </div>

                            </li>
                        }
                        @if (this.User.IsInRole("Administrator"))
                        {
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="All">Всички потребители</a>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>
                    @if (this.User!.Identity!.IsAuthenticated && !this.User.IsInRole("Administrator"))
                    {
                        <ul class="navbar-nav">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="All">Моите поръчки</a>
                        </ul>
                    }
                    else if (this.User.IsInRole("Administrator"))
                    {
                        <ul class="navbar-nav">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="All">Всички поръчки</a>
                        </ul>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <h6>За Фирмата</h6>
                    <p class="text-justify">
                        <strong>Технофорест ООД</strong>. Оторизиран дистрибутор на Хускварна груп.
                        Оторизиран Сервиз и Поддръжка.
                        Оригинални резервни части и аксесоари.
                        Повече от 25 години доказана фирма. 
                        <strong>Информация за контакт:</strong>
                        Бул. 23-ти Пехотен Шипченски Полк 16
                        Телефон: +359 (0) 888 321844
                    </p>
                </div>

                <div class="col-xs-6 col-md-3">
                    <h6>Продукти</h6>
                    <ul class="footer-links">
                        <li><a asp-controller="Automower" asp-action="All">Автоматични косачки</a></li>
                        <li><a asp-controller="Chainsaw" asp-action="All">Верижни триони</a></li>
                        <li><a asp-controller="LawnMower" asp-action="All">Косачки</a></li>
                        <li><a asp-controller="GrassTrimmer" asp-action="All">Моторни коси</a></li>
                        <li><a asp-controller="GardenTractor" asp-action="All">Градински трактори</a></li>
                    </ul>
                </div>

                <div class="col-xs-6 col-md-3">
                    <h6>Къде да ни намерите</h6>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2936.0417090532264!2d25.386598376618263!3d42.618071418761296!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40a853f7d67246f9%3A0x6b728625c852f65!2sUlitsa%20%2223-ti%20pehoten%20Shipchenski%20polk%22%2016%2C%206100%20Novenski%2C%20Kazanlak!5e0!3m2!1sen!2sbg!4v1691662079615!5m2!1sen!2sbg" width="270" height="150" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
            <hr>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <p class="copyright-text">
                        &copy; Tehnoforest - @ReleaseYear
                        @if (DateTime.UtcNow.Year != ReleaseYear)
                        {
                            @Html.Raw($" - {DateTime.UtcNow.Year}")
                        }
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Tehnoforest/Views/Shared/_NotificationsPartial.cshtml
@using static Tehnoforest.Common.NotificationMessagesConstants;

@if (TempData.ContainsKey(ErrorMessage))
{
    <script>toastr.error('@TempData[ErrorMessage]');</script>
}

@if (TempData.ContainsKey(WarningMessage))
{
    <script>toastr.warning('@TempData[WarningMessage]');</script>
}

@if (TempData.ContainsKey(InformationMessage))
{
    <script>toastr.info('@TempData[InformationMessage]');</script>
}

@if (TempData.ContainsKey(SuccessMessage))
{
    <script>toastr.success('@TempData[SuccessMessage]');</script>
}

Tehnoforest/Views/Shared/_RepairServiceProductPartial.cshtml
<head>
    <link rel="stylesheet" href="~/css/allProducts.css" />
</head>
@model RepairServiceProductAllViewModel
<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="https://www-static-nw.husqvarna.com/-/images/aprimo/husqvarna/service-environment/photos/action/wx-958305.jpg?v=570f424259e495dd&format=JPG_LANDSCAPE_COVER_MDl" alt="Chainsaw Image">
        <div class="card-body text-center">
            <h6>@Model.ClientName | @Model.BrandMachine | @Model.ModelMachine | @Model.DateReturned</h6>
            <a asp-controller="RepairServiceProduct" asp-action="Details" asp-route-id="@Model.Id"
               class="btn btn-success">Детайли</a>
        </div>
    </div>
</div>